"""EMR draft and minimal FHIR-like validation for the Paper II MVP."""

from __future__ import annotations

from typing import Any


def _patient_ref(case_id: str) -> str:
    return f"Patient/synthetic-{case_id}"


def build_emr_draft(state: dict[str, Any]) -> dict[str, Any]:
    return {
        "case_id": state["case_id"],
        "chief_complaint": state.get("symptom_text", ""),
        "symptom_entities": state.get("symptom_entities", []),
        "vision_findings": state.get("vision_tags", []),
        "assessment": "Evidence-aligned draft generated by Paper II MVP.",
        "evidence": state.get("kg_matches", []),
    }


def build_fhir_bundle(emr_draft: dict[str, Any], *, omit_observation: bool = False) -> dict[str, Any]:
    case_id = str(emr_draft["case_id"])
    entries = [
        {
            "fullUrl": f"urn:uuid:composition-{case_id}",
            "resource": {
                "resourceType": "Composition",
                "status": "preliminary",
                "title": "Paper II Synthetic EMR Draft",
                "type": {"text": "Synthetic multimodal EMR draft"},
                "subject": {"reference": _patient_ref(case_id)},
            }
        },
        {
            "fullUrl": f"urn:uuid:patient-{case_id}",
            "resource": {
                "resourceType": "Patient",
                "id": f"synthetic-{case_id}",
            }
        },
    ]
    if not omit_observation:
        entries.append(
            {
                "fullUrl": f"urn:uuid:observation-{case_id}",
                "resource": {
                    "resourceType": "Observation",
                    "status": "preliminary",
                    "code": {"text": "Multimodal symptom and vision findings"},
                    "subject": {"reference": _patient_ref(case_id)},
                    "valueString": emr_draft.get("assessment", ""),
                }
            }
        )
    return {"resourceType": "Bundle", "type": "document", "entry": entries}


def validate_fhir_bundle(bundle: dict[str, Any]) -> tuple[bool, list[str]]:
    errors: list[str] = []
    if bundle.get("resourceType") != "Bundle":
        errors.append("bundle.resourceType must be Bundle")
    if bundle.get("type") != "document":
        errors.append("bundle.type must be document")
    entries = bundle.get("entry", [])
    if not entries:
        errors.append("bundle.entry must not be empty")
    elif entries[0].get("resource", {}).get("resourceType") != "Composition":
        errors.append("first bundle entry must be Composition")
    resource_types = {
        entry.get("resource", {}).get("resourceType")
        for entry in entries
        if isinstance(entry, dict)
    }
    for required in ("Patient", "Composition", "Observation"):
        if required not in resource_types:
            errors.append(f"missing {required} resource")
    for entry in entries:
        resource = entry.get("resource", {})
        if resource.get("resourceType") in ("Composition", "Observation"):
            if not resource.get("subject", {}).get("reference"):
                errors.append(f"{resource.get('resourceType')} missing subject reference")
    return not errors, errors


def repair_fhir_bundle(bundle: dict[str, Any], emr_draft: dict[str, Any]) -> dict[str, Any]:
    repaired = dict(bundle)
    entries = list(repaired.get("entry", []))
    resource_types = {
        entry.get("resource", {}).get("resourceType")
        for entry in entries
        if isinstance(entry, dict)
    }
    if "Observation" not in resource_types:
        case_id = str(emr_draft["case_id"])
        entries.append(
            {
                "fullUrl": f"urn:uuid:observation-{case_id}",
                "resource": {
                    "resourceType": "Observation",
                    "status": "preliminary",
                    "code": {"text": "Repaired observation"},
                    "subject": {"reference": _patient_ref(case_id)},
                    "valueString": emr_draft.get("assessment", ""),
                }
            }
        )
    repaired["entry"] = entries
    repaired["type"] = "document"
    return repaired
